site:
  theme_color: "#0066cc"
  css_theme: t-Pac
  owner_link: http://www.agid.gov.it
  owner_logo: /img/agid-logo.svg
  partner_link: https://teamdigitale.governo.it
  privacy_link: https://developers.italia.it/it/privacy-policy
  gov_logo: /img/governo.svg
  partner_logo: /img/dt-logo.svg
  pill: alpha

  menu_items:
    - title: Dashboard
      url: /dashboard

  network_links:
    trasformazione_digitale:
      title: header_link_trasformazione
      url: 'https://pianotriennale-ict.italia.it'
      class: delimiter
      li_markup_pre: '<span class="u-block u-padding-all-s u-margin-top-xs u-color-grey-50 u-textUppercase">il programma</span>'
    developers:
      title: header_link_developers
      url: 'https://developers.italia.it/'
      li_markup_pre: '<span class="u-block u-padding-all-s u-margin-top-xs u-color-grey-50 u-textUppercase">le community</span>'
    design:
      title: header_link_design
      url: 'http://designers.italia.it'
      class: delimiter
    forum:
      title: header_link_forum
      url: 'https://forum.italia.it/'
      li_markup_pre: '<span class="u-block u-padding-all-s u-margin-top-xs u-color-grey-50 u-textUppercase">gli strumenti</span>'
    docs:
      title: header_link_docs
      url: 'https://docs.developers.italia.it/'
    github:
      title: header_link_github
      url: 'https://github.com/italia/'

  footer_links:
    privacy:
      title: footer_link_privacy
      url: '/privacy'
    legal_notes:
      title: footer_link_legal_notes
      url: '/note-legali'

  social:
    twitter:
      name: twitter
      link: https://twitter.com/DesignersITA
    medium:
      name: medium
      link: https://medium.com/designers-italia
