version: '3.7'

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
