version: "2"

services:

### Applications Code Container #############################

    application:
      image: tianon/true
      volumes:
        - ../:/var/www
        - ./logs:/var/log

### NGINX Server Container ##################################

    nginx:
      volumes:
        - /var/letsencrypt:/var/letsencrypt
        - /etc/ssl/certs:/etc/ssl/certs

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
    driver_opts:
      com.docker.network.driver.mtu: 1400
  backend:
    driver: "bridge"
    driver_opts:
      com.docker.network.driver.mtu: 1400
