name: Publish pre-release image

on:
  push:
    branches: [github_actions]
env:
  PHP_VERSION: 7.3
  IMAGE_TAG: test
  ORGANIZATION: webanalyticsitalia
  # REGISTRY: https://index.docker.io/v2/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- name: Pre
      #  run: |
      #    echo ${{ secrets.DOCKER_USERNAME }} - ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build image
        if: success()
        run: docker build --no-cache --rm -f ${{ github.workspace }}/Dockerfile.portal --build-arg PHP_VERSION=$PHP_VERSION -t $ORGANIZATION/wai-portal:$IMAGE_TAG ${{ github.workspace }}
      - name: Apply release tag >
        if: success()
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
          docker push $ORGANIZATION/wai-portal:$IMAGE_TAG
      - name: Docker logout
        if: always()
        run: docker logout
