name: Publish release portal image
on:
  release:
    types: [published]
env:
  PHP_VERSION: 7.4
  IMAGE_TAG: stable
  IMAGE_NAME: wai-portal
  ORGANIZATION: webanalyticsitalia
  K8S_CLIENT_CERT: ${{ secrets.K8S_CLIENT_CERT }}
  K8S_CLIENT_KEY: ${{ secrets.K8S_CLIENT_KEY }}
jobs:
  build:
    environment: public-playground
    runs-on: ubuntu-latest
    steps:
      - name: Set release image tag
        run: echo ::set-env name=RELEASE_TAG::$(echo ${{ github.ref }} | cut -c11-)
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        if: success()
        run: docker build --no-cache --rm -f ${{ github.workspace }}/Dockerfile.portal --build-arg PHP_VERSION=$PHP_VERSION -t $ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG ${{ github.workspace }}
      - name: Apply release tag
        if: success()
        run: docker tag $ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG $ORGANIZATION/$IMAGE_NAME:$RELEASE_TAG
      - name: Push image
        if: success()
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push $ORGANIZATION/$IMAGE_NAME:$RELEASE_TAG
          docker push $ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG
      - name: Docker logout
        if: always()
        run: docker logout
      - name: Get portal container index in its deployment
        if: success()
        run: |
          echo "PORTAL_CONTAINER_INDEX=$(curl -k \
          --silent \
          --cert <(echo "$K8S_CLIENT_CERT") \
          --key <(echo "$K8S_CLIENT_KEY") \
          -H 'Accept: application/json' \
          https://k8s.webanalytics.italia.it/apis/apps/v1/namespaces/wai-stag/deployments/portal \
          | jq '.spec.template.spec.containers | map(.name == "portal") | index(true)')" >> $GITHUB_ENV
      - name: Trigger portal rolling update in public-playground environment
        if: success()
        run: |
          curl -X PATCH \
            --silent \
            --output /dev/null \
            --cert <(echo "$K8S_CLIENT_CERT") \
            --key <(echo "$K8S_CLIENT_KEY") \
            -d @- \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json-patch+json' \
            https://k8s.webanalytics.italia.it/apis/apps/v1/namespaces/wai-play/deployments/portal <<EOF
          [
            { "op": "replace", "path": "/spec/template/spec/containers/${{ env.PORTAL_CONTAINER_INDEX }}/image", "value": "$ORGANIZATION/$IMAGE_NAME:$RELEASE_TAG" }
          ]
          EOF
      - name: Trigger portal-queue-worker rolling update in public-playground environment
        if: success()
        run: |
          curl -X PATCH \
            --silent \
            --output /dev/null \
            --cert <(echo "$K8S_CLIENT_CERT") \
            --key <(echo "$K8S_CLIENT_KEY") \
            -d @- \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json-patch+json' \
            https://k8s.webanalytics.italia.it/apis/apps/v1/namespaces/wai-play/deployments/portal-queue-worker <<EOF
          [
            { "op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "$ORGANIZATION/$IMAGE_NAME:$RELEASE_TAG" }
          ]
          EOF
      - name: Trigger portal-scheduler rolling update in public-playground environment
        if: success()
        run: |
          curl -X PATCH \
            --silent \
            --output /dev/null \
            --cert <(echo "$K8S_CLIENT_CERT") \
            --key <(echo "$K8S_CLIENT_KEY") \
            -d @- \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json-patch+json' \
            https://k8s.webanalytics.italia.it/apis/apps/v1/namespaces/wai-play/deployments/portal-scheduler <<EOF
          [
            { "op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "$ORGANIZATION/$IMAGE_NAME:$RELEASE_TAG" }
          ]
          EOF
